### ISSUE TITLE
Get latitude/longitude on mouse double click

### ISSUE THREAD

**Issue by alessandroAM** [raptorswing/MapGraphics#19]
Hello, any chance to know how to gather latitude/longitude when the user clicks on the map? I tried using the xyz2lla functions but they all return odd values. Thanks.

**Comment by kantooon** [comment]
Check project Qradiopredict for a sample implementation (now probably outdated).
You might need to rebase the code against latest upstream (this project).


On 6 December 2016 00:39:42 GMT, alessandroAM <notifications@github.com> wrote:
>Hello, any chance to know how to gather latitude/longitude when the
>user clicks on the map? I tried using the xyz2lla functions but they
>all return odd values. Thanks.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by alessandroAM** [comment]
Hello and thanks a lot for the quick reply, I followed your hint and got it done.
The only issue left that I have is the wheelEvent not working (actually it doesn't fire at all); so using the wheel mouse on the widget just makes it scroll on the vertical. But I suppose it's a Qt4.7/Mac related issue as I have seen countless users with the same QWheelEvent issue. Anyway, thanks again for this brilliant project and support!
