### ISSUE TITLE
Network Error: "Host otile1.mqcdn.com not found"

### ISSUE THREAD

**Issue by neel** [raptorswing/MapGraphics#20]
I am trying to run TestApp and I am getting the following error

> Network Error: "Host otile1.mqcdn.com not found"

**Comment by SomeoneElseOSM** [comment]
The background to this is that Mapquest's tiles went away a very long time ago.  Probably easiest just to remove the option.

**Comment by raptorswing** [comment]
Yes, unfortunately, MapQuest has discontinued their easy public tile access. I have updated the code to remove references to those tiles. Sorry for the delay.

At some point I would like to add the option to use Bing tiles - if anyone is looking for a project, I accept pull requests ;)
