### ISSUE TITLE
Tile references to openstreetmap.org should be https not http now.

### ISSUE THREAD

**Issue by SomeoneElseOSM** [raptorswing/MapGraphics#21]
This issue was prompted by reading https://stackoverflow.com/questions/48706399/mapgraphics-library-on-github-c-qt-openstreetmap .

The relevant bit to change is:

https://github.com/raptorswing/MapGraphics/blob/3ac9468cf4300611ba72a6e465bd37b65e028853/MapGraphics/tileSources/OSMTileSource.cpp#L109

given that the last commit was 3 years ago I'm logging this more to help library users than to expect a bug fix :)

**Comment by raptorswing** [comment]
HTTP is still working for me, but since HTTPS is available I have updated it. Thanks.

**Comment by SomeoneElseOSM** [comment]
Great stuff - thanks!
