### ISSUE TITLE
It’s good written code. 

### ISSUE THREAD

**Issue by munhktamir** [raptorswing/MapGraphics#23]
Sir, I am beginner of Qt. i am trying to add some position icon on center. But it doesn’t visible on MapGraphicView widget. How can i add it. Help me

**Comment by raptorswing** [comment]
Hi,

Sorry for the huge delay.

Please see:
https://github.com/raptorswing/MapGraphics/blob/e1f6b3bac344a3ceaab520e4ef542773f5a0a105/TestApp/MainWindow.cpp#L51-L56

for a simple example of how to add an object to the map.
